server:
  port: 3355
spring:
  application:
    name: cloud-config-client-3355

eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: ${config.eurekapath}
  instance:
    instance-id: cloud-config-client-3355
    #    #访问路径可以显示IP地址
    prefer-ip-address: true
