server:
  port: 8006


spring:
  application:
    name: consul-provider-payment

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.9.223:3306/db2019?characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: ablejava
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

mybatis:
    mapperLocations: classpath:mapper/*.xml
    type-aliases-package: com.able.springcloud.entities    # 所有Entity别名类所在包
