server:
  port: 8802
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                  virtual-host: /
                  host: 192.168.9.252
                  username: admin
                  password: admin
                  port: 5672
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchangeA # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置

  rabbitmq:
    virtual-host: /
    host: 192.168.9.252
    username: admin
    password: admin
    port: 5672

eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-stream-consumer-8082
    #    #访问路径可以显示IP地址
    prefer-ip-address: true