server:
  port: 80


eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-consumer-feign-hystrix-order-01
    #    #访问路径可以显示IP地址
    prefer-ip-address: true

spring:
  application:
    name: cloud-consumer-feign-hystrix-order
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000
#开启feigin对hystrix的支持
feign:
  hystrix:
    enabled: true
